### ISSUE TITLE
Surface position inaccuracy

### ISSUE THREAD

**Issue by hbokh** [mutability/dump1090#105]
The actual position of my receiver is 53.xyzN 6.xyzE

but somehow `dump1090-mutability` always puts it on 
https://goo.gl/maps/Ptc5SKC67cD2

which is like ~ 800m / half a mile up north.
It makes no difference in using more accuracy in the options, e.g. `--lat 53.xyz --lon 6.xyz` is giving the same position as `--lat 53.xyz --lon 6.xyz`.
Is this something I'm doing wrong or something else?

Cheers, Henk

PS Thanks for a great piece of software though!

**Comment by mutability** [comment]
Set --json-location-accuracy 2 if you want to report the exact receiver position; it is rounded for display by default for privacy reasons

**Comment by gonzalu** [comment]
Unable to set this variable in /etc/default/dump1090-mutability

I have tried using 
>JSON_LOCATION_ACCURACY="exact"

daemon still shows using option 1 (approximate)

Also, default should be 0 if not defined in config as per init.d script.

Thanks for your help
