### ISSUE TITLE
Hardware Abstraction Layer

### ISSUE THREAD

**Issue by shepherd007** [mutability/dump1090#113]
Today I tried to compile dump1090 natively for windows (I was surprised it worked - some specific functions such as nonsleep were stubbed without implementing anything). I am wondering; wouldn't be beneficial for future porting to add some kind of Hardware/Platform Abstraction Layer? Let's say - we have a few pthread functions that could be easily replaced by native windows calls - by adding common header with API declarations and implementation we could easily provide implementation specific for the OS (without 3rd party libraries). The same thing could apply to the networking.
I am rather thinking of covering low level system functions with HAL API than using #ifdef in the production code.

**Comment by mutability** [comment]
No fundamental objection so long as it doesn't mangle the existing code too much. There is something like it already going on for OSX / OpenBSD support (clock_gettime et al). If you want to build implementations of whatever Windows etc is missing, that's great. Do you have a list of what's needed?

**Comment by shepherd007** [comment]
Yeah, I've got some ideas - and since today I enabled networking on the windows (I really like the improvements on HTML GUI!) I'd like to push some of updates to windows_development branch - however it seems I have no push access. Could you please add me as a contributor?

**Comment by mutability** [comment]
I suggest you fork the repository and work in your copy, then use pull requests.

**Comment by shepherd007** [comment]
Here is a list of things I am seeing as a candidates for abstraction layer (for now):
- signaling - it looks that function such like initSignaling() would be enough both for posix and windows
- console operations - currently only clr() function is needed
- net_io.c is using directly close() function on the socket - it is also a good candidate to be reworked/moved to another file

**Comment by mutability** [comment]
Yeah, from looking through your pull request that list seems reasonable.
