### ISSUE TITLE
GPG Key expired

### ISSUE THREAD

**Issue by scottjl** [mutability/dump1090#119]
fresh install of mutability-repo_0.1.0_armhf.deb. apt-get update throws the following error:

`W: GPG error: http://repo.mutability.co.uk wheezy InRelease: The following signatures were invalid: KEYEXPIRED 1451307476 KEYEXPIRED 1451307476 KEYEXPIRED 1451307476`

Need an updated key?

**Comment by mutability** [comment]
Like the updated key which has been in 0.1.1 for the past 6 months, yes.

**Comment by scottjl** [comment]
ok, might want to update the git page:

`wget https://github.com/mutability/mutability-repo/releases/download/v0.1.0/mutability-repo_0.1.0_armhf.deb`
`sudo dpkg -i mutability-repo_0.1.0_armhf.deb`

to reflect the new file. thanks.

**Comment by mutability** [comment]
Thanks for pointing it out, the readme doesn't get much attention.
