### ISSUE TITLE
Extra configuration

### ISSUE THREAD

**Issue by evharten** [mutability/dump1090#121]
In previous dump1090's i always adjusted the planeObject.js to include the following in the update code:

`
        switch (this.icao)
        {
                case "484a91":
                        this.flight = "<font color=blue>PH-PXA_ZXP01</font>";
                        break;;
                case "484a92":
                        this.flight = "<font color=blue>PH-PXB_ZXP02</font>";
                        break;;
                case "484a93":
                        this.flight = "<font color=blue>PH-PXC_ZXP03</font>";
                        break;;
                case "484a94":
                        this.flight = "<font color=blue>PH-PXD_ZXP04</font>";
                        break;;
                case "484a95":
                        this.flight = "<font color=blue>PH-PXE_ZXP05</font>";
                        break;;
                case "484a96":
                        this.flight = "<font color=blue>PH-PXF_ZXP06</font>";
                        break;;
                case "484ac1":
                        this.flight = "<font color=blue>PH-PXY_ZXP25</font>";
                        break;;
                case "484ac0":
                        this.flight = "<font color=blue>PH-PXZ_ZXP26</font>";
                        break;;
                case "4844c2":
                        this.flight = "<font color=red>LIFELN1</font>";
                        break;;
                case "4843be":
                        this.flight = "<font color=red>LIFELN3</font>";
                        break;;
                case "484b58":
                        this.flight = "<font color=red>LIFELN2</font>";
                        break;;
                case "484c34":
                        this.flight = "<font color=red>LIFELN4</font>";
                        break;;
        }
`

This resulted in the planes tag to be set, and color them accordingly.
Blue for police helicopters, and red for the ambulance (trauma/lifeliner).

Is it possible to just make an array of some sort to set this ?

array(
'484b58' => ('LIFELN2', 'red'),
'484c34' => ('LIFELN4', 'red')
);

or something like that, that way we can add custom names to planes which in case of the Police and Lifeliners are usefull, as they are only trackable thru MLAT and provide no flight tag.

**Comment by mutability** [comment]
You could put the overrides in the static aircraft DB perhaps
