### ISSUE TITLE
Problem wth LAT and LON configuration option.

### ISSUE THREAD

**Issue by takenek** [mutability/dump1090#123]
Hello
I use newlatest version of dump1090 from Raspbian Repo (1.14).
I just saw dump1090 got problem with LAT and LON configuration Option.
On map show this same "My Radar site" but i give other places:
i try put my home possition look:
LAT="52.4146"
LON="20.9473"
i change to other place but show me on my map this same place.
LAT="52.405"
LON="20.947"

Best Regards
Marek

**Comment by mutability** [comment]
The map display rounds the position unless you set the location accuracy in the configuration to "exact".
