### ISSUE TITLE
2MHz demodulator removal prevents playback of binary files created at 2MHz

### ISSUE THREAD

**Issue by franhoran** [mutability/dump1090#128]
A recent change in dump1090.c (remove 2MHz demodulation) does not agree with example given in the README (use 2MHz modulation). 

https://github.com/mutability/dump1090/blob/master/README-dump1090.md says:

> The binary file should be created using rtl_sdr like this (or with any other program that is able to output 8-bit unsigned IQ samples at 2Mhz sample rate).
> rtl_sdr -f 1090000000 -s 2000000 -g 50 output.bin

"git log dump1090.c" says:

> commit 8f82e61f17bed05b62df5e828e23cd59d791d88f
> Author: Oliver Jowett oliver@mutability.co.uk
> Date:   Tue May 31 12:23:58 2016 +0100
>     Remove the 2MHz demodulator.
>     Now that the 2.4MHz demodulator does 3A/C there's no real reason
>     to keep the old demodulator around.

Fran

**Comment by mutability** [comment]
The docs are just out of date (README-dump1090 is just a direct copy of the upstream docs); capture at 2.4MHz.
