### ISSUE TITLE
weather overlay

### ISSUE THREAD

**Issue by imesg** [mutability/dump1090#135]
Request a weather radar overlay.

**Comment by mutability** [comment]
Do you have a source of map tiles for this?

**Comment by imesg** [comment]
No. But I will try to find one.

**Comment by imesg** [comment]
http://mesonet.agron.iastate.edu/ogc/

Good for US. I will look some more for world wide.

**Comment by mutability** [comment]
I added a NEXRAD layer. note that there's nothing special done for refreshing that, so it may be out of date / cached over time

**Comment by jthawkes** [comment]
NEXRAD looks great.

**Comment by imesg** [comment]
Outstanding.

**Comment by Romeo-Golf** [comment]
Would this be suitable for worldwide coverage?

http://openweathermap.org/hugemaps

**Comment by lwqcz** [comment]
What about windy maps? 😉 
https://www.windy.com/?radar,22.025,-18.633,3
