### ISSUE TITLE
Add option for all aircraft trails (vs selected aircraft)?

### ISSUE THREAD

**Issue by contactpb** [mutability/dump1090#138]
Hi,

Wondering if it would be possible to add an option to show aircraft trails for all visible aircraft (not just the selected one), or alternatively all trails since the browser window was opened?

Thanks,
Peter

**Comment by imesg** [comment]
Would like this as well.

Thanks,
Gene

**Comment by samwathegreat** [comment]
Agreed.  I would prefer an option to show all trails and either have a default or user-defined delay (seconds) for clearing the trail data since the aircraft was last seen.  I'm loving the new features (just updated a 2015 release).  Thanks!

**Comment by Romeo-Golf** [comment]
yes this would be nice, firstly to have the option to show the trail for every aircraft's entire flight.. or at least as much as was seen by dump1090...

And if this could be further enhanced to give the option to display trails for all aircraft, but limited to a user defined threshold of either time or distance :)

**Comment by impatientia** [comment]
Here's a quick hack that may achieve the desired effect.  It enables trails for all aircraft currently being tracked without having them clutter the screen forever.

in file /usr/share/dump1090-mutabilityscript.js, line 908
	comment out one line so that selecting and de-selecting planes won't clear the traces:
`//Planes[SelectedPlane].clearLines();`

in file /usr/share/dump1090-mutability/planeObject.js, at line 451
	comment out two lines so that all aircraft show trails
	`//if (!this.selected)`
	`//	return;`

It seems to work fine, but no testing has be done to validate long term stability.  And, of course, extra credit goes to whomever incorporates this as an option enabled/disabled through the UI.
