### ISSUE TITLE
dpkg-reconfigure rejects lat/lon of -0.1

### ISSUE THREAD

**Issue by jburgess777** [mutability/dump1090#14]
The is_number regex used to check the lat/lon fields rejects negative values between -1 and 0, e.g. -0.1 or -0.99. The problem occurs with any number beginning "-0".

**Comment by mutability** [comment]
Time to break out the jwz quote I think!

**Comment by mutability** [comment]
Hah, already used it, in relation to that code even! see https://github.com/mutability/dump1090/commit/55ecde9d5322458c736d1f022e60c9a1ac946fa4

**Comment by mutability** [comment]
As a workaround you can omit the lat/long from the question that asks for it, and instead specify --lat / --lon as "extra arguments" in the config question right at the end.
