### ISSUE TITLE
RSSI field seems incorrect

### ISSUE THREAD

**Issue by rf987** [mutability/dump1090#144]
Hello,

Today I installed and began using the dump1090-mutability v1.14 build.    Until today I've been using the original dump1090 software that has a "Sig" column displayed on the interactive screen.

With the original dump1090, the signal strength of "closer" aircraft would jump very high, from a 30 to a 150.  This happened consistently when aircraft would get close to my location.

On the dump1090-mutability v1.14 build however, the RSSI of all aircraft is relatively constant, only fluctuating between -33 to -35.  I never see the RSSI rise substantially when an aircraft is directly overhead.  Instead, the RSSI rises by a small fractional number ... ie, no substantial rise.

Is this a known bug?  

Thank you

**Comment by mutability** [comment]
1.14 is very old, please try current master
