### ISSUE TITLE
rings not centered.

### ISSUE THREAD

**Issue by arnauldb** [mutability/dump1090#152]
Hello,

thank you for dump1090.

I have a problem, how can I center the ring overlay or other overlays, heatmap, on my location ? I am in Paris but the overlays are centered on the Netherlands...

thank you,
![dump1090 - 7-17 41 0-s - chromium_002](https://cloud.githubusercontent.com/assets/13196747/19186867/9bbc1518-8c88-11e6-9d15-ef6160a5dca0.jpg)

**Comment by mutability** [comment]
You've made modifications to the dump1090 map UI. I can't provide support for those.

**Comment by Romeo-Golf** [comment]
Not sure if it's any help but I notice the distances are in the ~400km range which is about the distance from Paris to Amsterdam... 

Could it be that dump1090 has somehow been started with the -lat and -lon arguments containing coordinates from a location in the Netherlands? :)

**Comment by arnauldb** [comment]
thanks Romeo-Golf, you are right I started dump1090 with the wrong coordinates.
