### ISSUE TITLE
stats.json signal info only available on over sample

### ISSUE THREAD

**Issue by coolacid** [mutability/dump1090#159]
It appears that the code to generate signal power stats is only available in the 2.4 oversample file. 

Not sure if this is an oversight or technically not possible. Took me a while (both searching web and issues/code) to find the issue. 

To make it easier for people to find this ticket, some extra keywords:
peak_signal
strong_signals

**Comment by mutability** [comment]
I don't understand the problem; the 2.4MHz version is the only demodulator now.

**Comment by coolacid** [comment]
I was trying to figure out why I'm not getting as much signal as I thought I should be - part of this troubleshooting was changing the variable OVERSAMPLE in /etc/default/dump1090-mutability to "no" this caused the signals data to not be written to the json file.

**Comment by mutability** [comment]
OVERSAMPLE does exactly nothing in the current code and scripts, so you must be running an older version.
