### ISSUE TITLE
Skip the start dump1090 automatically question.

### ISSUE THREAD

**Issue by jprochazka** [mutability/dump1090#168]
When installing the dump1090-mutability package the user is asked if dump1090-mutability should be started automatically. Being that %99.9999 of the time this will be answered by a yes by the user is there a way to skip having to answer this question and have it default to yes so installation continues on uninterrupted?

**Comment by Romeo-Golf** [comment]
I would also find this useful ;)

**Comment by ralin3** [comment]
If you install debconf-utils, you can bypass it by preseeding the answer:
```
echo 'dump1090-mutability     dump1090-mutability/auto-start  boolean true' > /root/dump1090.seed
debconf-set-selections /root/dump1090.seed
```
Better to fix it of course, but at least it works for now.

**Comment by mutability** [comment]
That is in fact the right way to fix it - prepopulate the answer in the debconf db.

**Comment by Romeo-Golf** [comment]
cheers, as suggested the following appears to do trick:

> $ debconf-get-selections | grep "dump1090-mutability/auto-start"
> dump1090-mutability     dump1090-mutability/auto-start  boolean false
>
> $ echo 'dump1090-mutability     dump1090-mutability/auto-start  boolean true' | debconf-set-selections -v
> info: Trying to set 'dump1090-mutability/auto-start' [boolean] to 'true'
> info: Loading answer for 'dump1090-mutability/auto-start'
> 
> $ debconf-get-selections | grep "dump1090-mutability/auto-start"
> dump1090-mutability     dump1090-mutability/auto-start  boolean true
 >

:)
