### ISSUE TITLE
Multi feed Identifier

### ISSUE THREAD

**Issue by jjx-** [mutability/dump1090#175]
Hi,
I have a setup where multiple ADS-B streams from different raspberrys are visualised in one master instance (dump1090 without own receiver). I successfully got RSSI displayed in the main instance by switching from RAW to Beast. I am now in search for a way to display the name or a uniqe identifier to see which reciver is 'seeing' the machine and is transmitting the data.
Is the an option I am not aware of?

**Comment by mutability** [comment]
This data is not in the datafeed itself and dump1090 doesn't distinguish different connections, so no, you currently can't do that.
