### ISSUE TITLE
Ability to orientate the map to a heading other than North

### ISSUE THREAD

**Issue by Romeo-Golf** [mutability/dump1090#176]
As google maps allows you to originate the map to a heading other than 0 degrees I was just wondering if it would be possible to do the same with the map displayed by dump1090?

Thanks.

**Comment by mutability** [comment]
alt+shift+drag

**Comment by Romeo-Golf** [comment]
Would it be possible to configure the map heading in the config so that it orientates itself on startup without requiring user intervention?

**Comment by mutability** [comment]
Sure, I'd take a pull request which persists that.

(Do it like the other persistent settings i.e. browser local storage, config file probably doesn't make sense)
