### ISSUE TITLE
Non-Issue (at present) - Ensure conformity with explicit LSB definitions

### ISSUE THREAD

**Issue by Romeo-Golf** [mutability/dump1090#186]
While following Debian interpretations of the standards defined by the LSB should result in reliable operation on pure Debian installs and closely related distributions such as Ubuntu, this may not necessarily be the case on embedded/SoC platforms which may only run on their own Debian derived distribution..

As discussed at length in Issue #172 then Pull Request #185, issues have been observed on the C.H.I.P. platform which appear to result from their interpretation of the LSB being somewhat more strict than Debian's...

Hopefully the addition of $network will resolve the issues report in #172, and while I do not disagree that on most implementations its likely that all of the local file systems should be mounted by the time the remote file systems explicitly required for the $remote_fs criteria to be met, I figured it was worth having an issue logged which can be refereed to should there be any other reports of similar problems on distributions which appear to follow the explicit LSB definitions :)

**Comment by mutability** [comment]
You didn't actually put what you wanted changed in this issue. I assume you want $local_fs in addition to $remote_fs.

Can you give me a concrete example of a distribution where $local_fs is required in addition to $remote_fs for the initscript to operate correctly?
