### ISSUE TITLE
interactive TTL ignored

### ISSUE THREAD

**Issue by philipz-59** [mutability/dump1090#195]
How to use this parameter? When specifying ./dump1090 --interactive --interactive-ttl 50000,
aircrafts are discarded after 300 sec, whereas dump1090_antirez works as desired..
Regards!

**Comment by mutability** [comment]
Are you trying to set a timeout of 50s or 50,000s?

**Comment by philipz-59** [comment]
As described in help, trying to set a timeout to 50000 seconds.
Now I bisected problem, everything above 300s is discarded..

**Comment by mutability** [comment]
The main tracking logic has a hardcoded timeout of 300s; if you want to display aircraft older than that, you'll need to increase that timeout (TRACK_AIRCRAFT_TTL in track.h) and rebuild.

**Comment by philipz-59** [comment]
Ok. And where can I setup prolonged aircraft visibility for web frontend? Default is also 60 seconds.
Regards!

**Comment by philipz-59** [comment]
aircraft visibility.. ;)

**Comment by mutability** [comment]
There's no one place, you'll have to dig through the javascript

**Comment by philipz-59** [comment]
Consider it closed, regards!
