### ISSUE TITLE
Can't access Web using source version.

### ISSUE THREAD

**Issue by jmceara** [mutability/dump1090#197]
Hi.
I just cloned git version and compiled in my SO (linaro). Just needed to change compiler flag '-std=c11' to 'gnu99' and everything is workig fine! Almost....
Webinterface is not working. I can access it (compiled with -DENABLE_WEBSERVER and started with --net), but screen keeps on spinning logo and doesn't show map, just loading screen.
Tested with firefox/chrome/IE.

Any update avilable for web files?! Any way to debug it?
When using firebug to debug web, got this error:
"Style sheet could not be loaded. http://192.168.22.113:8080/ol3/ol3-layerswitcher.css"

But If I access this URL (on web brownser), I can access it normally.

**Comment by mutability** [comment]
The internal webserver is not supported; you're on your own. I recommend using an external webserver.
