### ISSUE TITLE
GPG error http://repo.mutability.co.uk The following signatures were invalid: KEYEXPIRED

### ISSUE THREAD

**Issue by takenek** [mutability/dump1090#198]
W: GPG error: http://repo.mutability.co.uk wheezy InRelease: The following signatures were invalid: KEYEXPIRED 1495751596 KEYEXPIRED 1495751596 KEYEXPIRED 1495751596 KEYEXPIRED 1495751596 KEYEXPIRED 1495751596

**Comment by mutability** [comment]
This repo is unmaintained and I have just removed the dns name for it; please build from source.
