### ISSUE TITLE
Config for Apache 2.4

### ISSUE THREAD

**Issue by elmicha** [mutability/dump1090#203]
If you have an existing Apache 2.4 install and want to see dump1090 at http://localhost/dump1090, save the following lines to /etc/apache2/sites-available/dump1090.conf and run `sudo a2ensite dump1090` afterwards:

```
Alias "/dump1090/data" "/run/dump1090-mutability"
<Directory "/run/dump1090-mutability">
    Require all granted
</Directory>

Alias "/dump1090" "/usr/share/dump1090-mutability/html"
<Directory "/usr/share/dump1090-mutability/html">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex gmap.html
</Directory>
```

**Comment by E3V3A** [comment]
This didn't work for me. What exact steps did you take before?

**Comment by elmicha** [comment]
After `dpkg-buildpackage -b` you need to install the package: 

    cd ..
    sudo dpkg -i dump1090-mutability_1.15~dev_amd64.deb
