### ISSUE TITLE
Add plausibility check for CRC-corrected frames

### ISSUE THREAD

**Issue by helioshk** [mutability/dump1090#215]
I've just captured a helicopter at 93'100ft, which I think is unlikely to be true :)
Big jumps in altitude or position should be rejected.

**Comment by mutability** [comment]
The rule of thumb here is to still produce the raw frames themselves, but do any plausibility checking in the tracking layer. This is already done for positions. Altitude/vrate checks could also be done there.

What's the underlying message that gave you the bad altitude? DF4/20 don't do CRC correction anyway.

**Comment by helioshk** [comment]
Oh ok. I don't have the message, I just saw it on the web interface.
