### ISSUE TITLE
dump1090 & rtl_tcp at the same Time

### ISSUE THREAD

**Issue by martenumberto** [mutability/dump1090#225]
Hello,

just wondering if it's possible to run dump1090 at the same time with rtl_tcp.
I want to feed Data to FR24 and also want to hear some frequencies with SDR#.
When i enable the Raw Port, i can connect with SDR# but there is no tuning?
Is it because the Tuner is already in use?

**Comment by mutability** [comment]
No, this is not possible; the tuner can only tune to one frequency at a time.
