### ISSUE TITLE
Switch between dump1090 and rtl_tcp

### ISSUE THREAD

**Issue by martenumberto** [mutability/dump1090#226]
Hello,

usually i run dump1090 on my pi to upload the data to Fr24. But sometimes I want to hear some Radio with rtl_tcp. When I quit dump1090 and run rtl_test everything is fine. But when I run rtl_tcp it quits with an error:
"rtl_tcp: symbol lookup error: rtl_tcp: undefined symbol: rtlsdr_set_bias_tee"

I think the problem is librtlsdr. When I deinstall it and remove the libs from /usr/local/lib, rtl_tcp runs fine again. But now dump1090 is broken because of the missing librtlsdr.

Any ideas to solve the problem? 
In the second step I want to create a script which switches easily between dump1090 and rtl_tcp

**Comment by marcus-aa** [comment]
Buy a second dongle. They should have different antennas anyways...

**Comment by mutability** [comment]
The link problem is because you have more than one version of librtlsdr installed (rtl_tcp is built against one version, dump1090 against the other)

**Comment by martenumberto** [comment]
What can I do to solve it? I've bought a second sdr stick and I want to run dump1090 and rtl_tcp

**Comment by mutability** [comment]
Pick one version of rtlsdr to use, make sure only that version is installed, and make sure that both dump1090 and rtl_tcp were built against that version
