### ISSUE TITLE
Eurocontrol Maastricht Upper Area Control (MUAC) map overlay

### ISSUE THREAD

**Issue by PW00X** [mutability/dump1090#230]
Needless to say I love dump1090 and like most people especially this fork.

As I'm not to powerful on webcodding I was wondering if someone could guide me to integrate the MUAC charts as an **overlay** for OpenStreeMap.
These "images", actually they are originally PDF, are available on the [Eurocontrol website](http://www.eurocontrol.int/articles/atc-charts) especially the [Maastricht UAC Sectorisation chart](http://www.eurocontrol.int/sites/default/files/article/content/documents/muac/charts/102-0271_180329.pdf) is interesting to me personally as this is the region my install is active and combined with an airband scanner.

Regards,
PW00X

**Comment by mutability** [comment]
PDFs are going to be hard to work with. If you can get the maps into a tiled bitmap format, though, then that's fairly easy to add as a new layer.

**Comment by HNJAMeindersma** [comment]
Not in any easy way. You would need to convert them like @mutability said, cut them up and then find a way to import them with the OpenStreetMap javascript library (CMIIW).
