### ISSUE TITLE
not working with the latest version of Stretch

### ISSUE THREAD

**Issue by namettt** [mutability/dump1090#232]
I recently installed the latest version of Raspbian stretch and downloaded mutability v1.14. The problem is it doesn't work on it. I have double checked it on the older Raspbian version to make sure I wasn't making any mistakes. Works fine there. I then downloaded dump1090-fa to the latest Stretch and it works fine as well. 

Can you please look into it?

**Comment by sweetpants** [comment]
Try 1.15-dev, it is working for me on the latest Stretch

**Comment by IT-Berater** [comment]
1.15-dev is working with Stretch, see http://blog.wenzlaff.de/?p=6195
