### ISSUE TITLE
decode mode A/C in --oversample mode

### ISSUE THREAD

**Issue by hhm0** [mutability/dump1090#37]
It would be wonderful to support this! :-)

**Comment by mutability** [comment]
No fundamental reason this can't be done, it's just not high on my list at the moment.

**Comment by jester-xbmc** [comment]
Bump ? ;)

**Comment by mutability** [comment]
I got as far as deciding that tracking phase in terms of a 60MHz clock seems to be the way to go, but no further at the moment.

(at 60MHz, a mode A/C bit is 27 cycles on + 60 cycles off, and each 2.4MHz sample is 25 cycles wide)

**Comment by mutability** [comment]
I put together something quick here: https://github.com/mutability/dump1090/tree/modeac
It seems to decode some stuff at least..

Be aware that you will need quite a lot more CPU to process Mode A/C (partly to run the demodulator, partly because there are some scaling problems in the original mode a/c tracking code that I have not looked at yet - the cost goes up with the square of the number of tracked aircraft)

**Comment by jester-xbmc** [comment]
Thanks for the work, i'll have a play, more CPU meaning a pi3 is out ?

**Comment by mutability** [comment]
It's fine on a Pi 3 (~25% CPU), probably a Pi 2 is OK too (haven't tried), but my Pi 1B+ was running out of CPU.

**Comment by mutability** [comment]
Also the demodulator is currently tuned to be quite aggressive about rejecting noise since there's no real way to validate a mode a/c message (no error detection/correction at all). With my test site here it's only decoding 15-20% as many messages as the original 2MHz decoder, but the original decoder has a real problem with junk messages here (half the interactive display is junk with A/C on)

**Comment by jester-xbmc** [comment]
Thanks, Understood, I have a spare pi3 on the way so I can do some testing.

**Comment by jthawkes** [comment]
How do I compile and install it? I can't seem to git clone it.

**Comment by mutability** [comment]
It's a branch:

```
$ git clone https://github.com/mutability/dump1090.git -b modeac
```

**Comment by jthawkes** [comment]
That worked. Site 20037 updated.
Thanks. Not too familiar with github, other than having to block it at work for several months.
ADS-B CPU on RPI3 went from 10-15%(collectd graphs). Overall CPU has hardly changed.

**Comment by mutability** [comment]
This seems stable enough that I think I'll go ahead and apply it to master.

**Comment by jester-xbmc** [comment]
look good here, i'd say bump to master, thanks for the effort !

**Comment by jthawkes** [comment]
My "Tracks with Single messages" graph increased significantly.
It increased about 6 fold. The same for unique tracks.

**Comment by mutability** [comment]
Yes. Mode A/C can't really be error-checked so you will be getting all sorts of noise.

**Comment by mutability** [comment]
What I would be interested in is someone to actually look at whether the A/C data is _useful_
(it's not very interesting here because almost everything is Mode S too)

**Comment by jester-xbmc** [comment]
Its useful tracking mil aircraft, think B-52 (no mode-s)

**Comment by mutability** [comment]
Sure. How well do the changes work for that?

**Comment by jester-xbmc** [comment]
well previous mode a/c was ok, but I havent used it as I run oversampled as default, so bit tricky to compare, always i'm waiting for a "juicy target" ;)

**Comment by jthawkes** [comment]
Mode C will still be used in the US and Aus for a while. Not so much for Commercial traffic but definately for GA traffic. The US mandate doesn't come into effect until 2020. Even then, only where Mode C transponders are currently required.
Aus will require ADS-B for IFR from next year, I think. VFR won't require it for quite a while.

**Comment by mutability** [comment]
Yes, I understand all this. What I am asking for is for people in areas where Mode A/C is actually interesting (that's you, guys!) to give me some feedback on whether the 2.4MHz demodulator is working well or not. All I can test here is that I get a bunch of A/C returns that match up with the Mode S returns and a low rate of garbage messages. There are few A/C-only aircraft I can test against here.

**Comment by jester-xbmc** [comment]
i'm in the same boat, although I'm trying to use this for mode a/c only aircraft, they are much more common in the US, however lots of US mil aircraft movements here lately so I hope to be able to report something useful soon for you.

**Comment by jthawkes** [comment]
Hmm, I thought mode Es were suppose to broadcast mode C for quite a while. I think it is needed for tcas. 
I think it is hard to see Mode C traffic. Need others to be sending the info to mlat so we can get a position fix. I can see some info using view1090-mutability --modeac
~001172 A     1172                                             -50.0     6 43
~007777 A     7777                                             -50.0     8 10

I have seen a few comments in the forums about people not seeing their friend's Mode C only IFR flight. They said it used to work.

**Comment by sbcaron** [comment]
Running on sites 6173 and 6232 located in Southern California. RPI 2 B. CPU up about 5% per collectd graphs.
Like jthawkes, Unique and Single tracks increased by 6 to 10 times.
This is a portion of my listing using view1090-mutability --modeac:
~005673 A     5673  
~001145 A     1145  
~006315 A     6315  
 A8E1F6 S ac  3346  
 A4DD02 S  c  
 A84CE2 S  c  3557

Are the A and C only aircraft supposed to show list of tracked aircraft?
--Steve

**Comment by mutability** [comment]
This is on master now.

**Comment by hhm0** [comment]
Thank you so much! Working well here so far, without any noticeable
error returns.
