### ISSUE TITLE
include rtl_test with your librtl deployment

### ISSUE THREAD

**Issue by jester-xbmc** [mutability/dump1090#49]
Could you include rtl_test in your librtlsdr deployment ? its mentioned in your install documentation.

If you do a clean install it would help to have this available so you can do ppm offset calculations without having to install and compile it yourself.

**Comment by mutability** [comment]
It's already packaged as rtl-sdr?

**Comment by jester-xbmc** [comment]
I meant when one goes into script kiddy mode and follow your readme and wants to install dump1090 on a clean raspbian you do:
wget https://github.com/mutability/mutability-repo/releases/download/v0.1.0/mutability-repo_0.1.0_armhf.deb
sudo dpkg -i mutability-repo_0.1.0_armhf.deb
sudo apt-get install dump1090-mutability

Which doesn't install rtl_test but you refer to it in the same readme :)
so suggestion was to either add it to librtl and/or add it to the readme as a sudo apt-get install rtl-sdr
or just ignore this call me OCD ;)
