### ISSUE TITLE
Add a gain-scanning mode

### ISSUE THREAD

**Issue by mutability** [mutability/dump1090#7]
Count messages for short periods with different gain settings and accumulate the results, display the results in a table, suggest the best gain value to set.

**Comment by keptenkurk** [comment]
Would be cool feature. Maybe record furthest seen as well in that table? 
Might be feature for web page / json export anyway: furthest seen last 10 minutes?

**Comment by mutability** [comment]
I'm thinking of a scanning hop interval of around 1 second so I don't think position data is going to be reliable (you need 2 messages to get a global position, and they're sent at most 2/second)

The webmap does the distance calculation itself anyway already

**Comment by keptenkurk** [comment]
Agree on that. Looking forward to this scanning feature!

**Comment by Romeo-Golf** [comment]
This would be great all the folks with tuners that perform better with a gain value other than maximum, has there been any further interest in this functionality?
