### ISSUE TITLE
Enable HTTP server from command line + any non-Debian gotchas?

### ISSUE THREAD

**Issue by roger-** [mutability/dump1090#72]
I might be missing something, but how do I enable the builtin HTTP server from the command line?

Also I'm considering running this on a non-Debian system (OpenWrt), are there any potential incompatibilities compared to MalcolmRobb/dump1090?

Thanks!

**Comment by mutability** [comment]
--net --net-http-port (whatever port)

I have not tested on OpenWrt so I can't really say; there is no packaging for it, but it should build from source OK.
