### ISSUE TITLE
apt-get install throws error when user 'debian' already exists

### ISSUE THREAD

**Issue by MartijnvdB** [mutability/dump1090#88]
Hi,

Thanks for this great fork. I've been playing with a manually compiled version and decided to try the package today.

Installing latest with:

root@beaglebone:~# apt-get install dump1090-mutability
[...]
Setting up dump1090-mutability (1.14) ...
adduser: The user `debian' already exists. Exiting.
dpkg: error processing dump1090-mutability (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dump1090-mutability
E: Sub-process /usr/bin/dpkg returned an error code (1)

Obviously, I already have a user 'debian' on the system.
Manual configuration fails with:

root@beaglebone:~# dpkg-reconfigure dump1090-mutability
/usr/sbin/dpkg-reconfigure: dump1090-mutability is broken or not fully installed

Is there a way around this?

Thanks,

Martijn

**Comment by mutability** [comment]
This is the same as issue #24.

As a workaround, purge the package (apt-get remove --purge), reinstall, and don't specify a system user when reconfiguring.
