### ISSUE TITLE
Errors were encountered while processing: dump1090-mutability

### ISSUE THREAD

**Issue by jprochazka** [mutability/dump1090#92]
For completeness I am posting the output of the build as well as the error encountered when trying to install the package. I am building and installing dump1090-mutability on a clean installation of a fully updated Debian Jessie in an amd64 environment.

The build looks good.

joe@debian:~/dump1090$ dpkg-buildpackage -b
dpkg-buildpackage: source package dump1090-mutability
dpkg-buildpackage: source version 1.15~dev
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by Oliver Jowett oliver@mutability.co.uk
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build dump1090
 fakeroot debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
        make -j1 clean
make[1]: Entering directory '/home/joe/dump1090'
rm -f _.o compat/clock_gettime/_.o compat/clock_nanosleep/_.o dump1090 view1090 faup1090 cprtests crctests
make[1]: Leaving directory '/home/joe/dump1090'
   dh_clean
        rm -f debian/dump1090-mutability.substvars
        rm -f debian/dump1090-mutability._.debhelper
        rm -rf debian/dump1090-mutability/
        rm -f debian/_.debhelper.log
        rm -f debian/files
        find .  ( ( \
                ( -path .\_/.git -o -path .*/.svn -o -path .*/.bzr -o -path .*/.hg -o -path .*/CVS ) -prune -o -type f -a \
                ( -name '#_#' -o -name '._~' -o -name '_~' -o -name DEADJOE \
                 -o -name '_.orig' -o -name '_.rej' -o -name '_.bak' \
                 -o -name '._.orig' -o -name ._.rej -o -name '.SUMS' \
                 -o -name TAGS -o ( -path '_/.deps/_' -a -name '_.P' ) \
                ) -exec rm -f {} + ) -o \
                ( -type d -a -name autom4te.cache -prune -exec rm -rf {} + ) )
        rm -f *-stamp
 debian/rules build
dh build
   dh_testdir
   dh_auto_configure
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/joe/dump1090'
dh_auto_build -- 'EXTRACFLAGS=-DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\"'
        make -j1 "EXTRACFLAGS=-DHTMLPATH=\\"/usr/share/dump1090-mutability/html\\" -DMODES_DUMP1090_VARIANT=\\"dump1090-mutability\\""
make[2]: Entering directory '/home/joe/dump1090'
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W `pkg-config --cflags librtlsdr` -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c dump1090.c -o dump1090.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c anet.c -o anet.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c interactive.c -o interactive.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c mode_ac.c -o mode_ac.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c mode_s.c -o mode_s.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c net_io.c -o net_io.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c crc.c -o crc.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c demod_2000.c -o demod_2000.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c demod_2400.c -o demod_2400.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c stats.c -o stats.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c cpr.c -o cpr.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c icao_filter.c -o icao_filter.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c track.c -o track.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c util.c -o util.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c convert.c -o convert.o
gcc -g -o dump1090 dump1090.o anet.o interactive.o mode_ac.o mode_s.o net_io.o crc.o demod_2000.o demod_2400.o stats.o cpr.o icao_filter.o track.o util.o convert.o -lpthread -lm -lrt `pkg-config --libs librtlsdr` -fPIE -pie -Wl,-z,relro -Wl,-z,now
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W -DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" -c view1090.c -o view1090.o
gcc -g -o view1090 view1090.o anet.o interactive.o mode_ac.o mode_s.o net_io.o crc.o stats.o cpr.o icao_filter.o track.o util.o -lpthread -lm -lrt -fPIE -pie -Wl,-z,relro -Wl,-z,now
make[2]: Leaving directory '/home/joe/dump1090'
make[1]: Leaving directory '/home/joe/dump1090'
   dh_auto_test
        make -j1 test
make[1]: Entering directory '/home/joe/dump1090'
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W  -c cprtests.c -o cprtests.o
gcc -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION=\"v1.15~dev\" -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -Wall -Werror -W  -g -o cprtests cpr.o cprtests.o -lm
./cprtests
testCPRGlobalAirborne[0,EVEN]: PASS
testCPRGlobalAirborne[0,ODD]:  PASS
testCPRGlobalAirborne[1,EVEN]: PASS
testCPRGlobalAirborne[1,ODD]:  PASS
testCPRGlobalSurface[0,EVEN]:  PASS
testCPRGlobalSurface[0,ODD]:   PASS
testCPRGlobalSurface[1,EVEN]:  PASS
testCPRGlobalSurface[1,ODD]:   PASS
testCPRGlobalSurface[2,EVEN]:  PASS
testCPRGlobalSurface[2,ODD]:   PASS
testCPRGlobalSurface[3,EVEN]:  PASS
testCPRGlobalSurface[3,ODD]:   PASS
testCPRGlobalSurface[4,EVEN]:  PASS
testCPRGlobalSurface[4,ODD]:   PASS
testCPRGlobalSurface[5,EVEN]:  PASS
testCPRGlobalSurface[5,ODD]:   PASS
testCPRGlobalSurface[6,EVEN]:  PASS
testCPRGlobalSurface[6,ODD]:   PASS
testCPRGlobalSurface[7,EVEN]:  PASS
testCPRGlobalSurface[7,ODD]:   PASS
testCPRGlobalSurface[8,EVEN]:  PASS
testCPRGlobalSurface[8,ODD]:   PASS
testCPRGlobalSurface[9,EVEN]:  PASS
testCPRGlobalSurface[9,ODD]:   PASS
testCPRGlobalSurface[10,EVEN]:  PASS
testCPRGlobalSurface[10,ODD]:   PASS
testCPRGlobalSurface[11,EVEN]:  PASS
testCPRGlobalSurface[11,ODD]:   PASS
testCPRGlobalSurface[12,EVEN]:  PASS
testCPRGlobalSurface[12,ODD]:   PASS
testCPRGlobalSurface[13,EVEN]:  PASS
testCPRGlobalSurface[13,ODD]:   PASS
testCPRGlobalSurface[14,EVEN]:  PASS
testCPRGlobalSurface[14,ODD]:   PASS
testCPRGlobalSurface[15,EVEN]:  PASS
testCPRGlobalSurface[15,ODD]:   PASS
testCPRGlobalSurface[16,EVEN]:  PASS
testCPRGlobalSurface[16,ODD]:   PASS
testCPRGlobalSurface[17,EVEN]:  PASS
testCPRGlobalSurface[17,ODD]:   PASS
testCPRGlobalSurface[18,EVEN]:  PASS
testCPRGlobalSurface[18,ODD]:   PASS
testCPRGlobalSurface[19,EVEN]:  PASS
testCPRGlobalSurface[19,ODD]:   PASS
testCPRGlobalSurface[20,EVEN]:  PASS
testCPRGlobalSurface[20,ODD]:   PASS
testCPRGlobalSurface[21,EVEN]:  PASS
testCPRGlobalSurface[21,ODD]:   PASS
testCPRGlobalSurface[22,EVEN]:  PASS
testCPRGlobalSurface[22,ODD]:   PASS
testCPRRelative[0]:  PASS
testCPRRelative[1]:  PASS
testCPRRelative[2]:  PASS
testCPRRelative[3]:  PASS
testCPRRelative[4]:  PASS
testCPRRelative[5]:  PASS
testCPRRelative[6]:  PASS
testCPRRelative[7]:  PASS
testCPRRelative[8]:  PASS
testCPRRelative[9]:  PASS
testCPRRelative[10]:  PASS
testCPRRelative[11]:  PASS
testCPRRelative[12]:  PASS
testCPRRelative[13]:  PASS
testCPRRelative[14]:  PASS
testCPRRelative[15]:  PASS
testCPRRelative[16]:  PASS
testCPRRelative[17]:  PASS
testCPRRelative[18]:  PASS
testCPRRelative[19]:  PASS
testCPRRelative[20]:  PASS
testCPRRelative[21]:  PASS
testCPRRelative[22]:  PASS
testCPRRelative[23]:  PASS
testCPRRelative[24]:  PASS
testCPRRelative[25]:  PASS
testCPRRelative[26]:  PASS
testCPRRelative[27]:  PASS
testCPRRelative[28]:  PASS
testCPRRelative[29]:  PASS
make[1]: Leaving directory '/home/joe/dump1090'
 fakeroot debian/rules binary
dh binary
   dh_testroot
   dh_prep
        rm -f debian/dump1090-mutability.substvars
        rm -f debian/dump1090-mutability._.debhelper
        rm -rf debian/dump1090-mutability/
   dh_auto_install
        install -d debian/dump1090-mutability
   debian/rules override_dh_install
make[1]: Entering directory '/home/joe/dump1090'
dh_install
        install -d debian/dump1090-mutability/usr/share/dump1090-mutability/html
        cp -a ./public_html/config.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/coolclock debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/dbloader.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/flags-tiny debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/flags.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/formatter.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/gmap.html debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/markers.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/planeObject.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/script.js debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/spinny.gif debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        cp -a ./public_html/style.css debian/dump1090-mutability/usr/share/dump1090-mutability/html/
        install -d debian/dump1090-mutability/etc/lighttpd/conf-available
        cp -a ./debian/lighttpd/89-dump1090.conf debian/dump1090-mutability/etc/lighttpd/conf-available/
        install -d debian/dump1090-mutability/etc/nginx/sites-available
        cp -a ./debian/nginx/dump1090-mutability debian/dump1090-mutability/etc/nginx/sites-available/
        cp -a ./debian/config-template debian/dump1090-mutability/usr/share/dump1090-mutability/
        cp -a ./debian/cron-template debian/dump1090-mutability/usr/share/dump1090-mutability/
        cp -a ./tools/vrs-basicaircraft-to-json.py debian/dump1090-mutability/usr/share/dump1090-mutability/
        cp -a ./tools/update-aircraft-database.sh debian/dump1090-mutability/usr/share/dump1090-mutability/
install -d debian/dump1090-mutability/usr/bin
cp -a dump1090 debian/dump1090-mutability/usr/bin/dump1090-mutability
cp -a view1090 debian/dump1090-mutability/usr/bin/view1090-mutability
make[1]: Leaving directory '/home/joe/dump1090'
   dh_installdocs
        install -g 0 -o 0 -d debian/dump1090-mutability/usr/share/doc/dump1090-mutability
        install -g 0 -o 0 -m 644 -p debian/copyright debian/dump1090-mutability/usr/share/doc/dump1090-mutability/copyright
   dh_installchangelogs
        install -o 0 -g 0 -p -m644 debian/changelog debian/dump1090-mutability/usr/share/doc/dump1090-mutability/changelog
   dh_installdebconf
        install -o 0 -g 0 -d debian/dump1090-mutability/DEBIAN
        sed s/#DEBHELPER#// < debian/dump1090-mutability.config > debian/dump1090-mutability/DEBIAN/config
        chown 0:0 debian/dump1090-mutability/DEBIAN/config
        chmod 755 debian/dump1090-mutability/DEBIAN/config
        install -o 0 -g 0 -m 644 -p debian/dump1090-mutability.templates debian/dump1090-mutability/DEBIAN/templates
        (grep -s -v misc:Depends debian/dump1090-mutability.substvars; echo "misc:Depends=debconf (>= 0.5) | debconf-2.0") > debian/dump1090-mutability.substvars.new
        mv debian/dump1090-mutability.substvars.new debian/dump1090-mutability.substvars
        echo "# Automatically added by dh_installdebconf">> debian/dump1090-mutability.postrm.debhelper
        sed "" /usr/share/debhelper/autoscripts/postrm-debconf >> debian/dump1090-mutability.postrm.debhelper
        echo '# End automatically added section' >> debian/dump1090-mutability.postrm.debhelper
   dh_pysupport
dh_pysupport: This program is deprecated, you should use dh_python2 instead. Migration guide: http://deb.li/dhs2p
        /usr/share/python-support/private/movemodules debian/dump1090-mutability
        rm -f vrs-basicaircraft-to-json.pyc vrs-basicaircraft-to-json.pyo
        mkdir -p -m 755 debian/dump1090-mutability/usr/share/python-support
        (grep -s -v python:Depends debian/dump1090-mutability.substvars; echo "python:Depends=python-support (>= 0.90.0)") > debian/dump1090-mutability.substvars.new
        mv debian/dump1090-mutability.substvars.new debian/dump1090-mutability.substvars
        (grep -s -v python:Depends debian/dump1090-mutability.substvars; echo "python:Depends=python, python-support (>= 0.90.0)") > debian/dump1090-mutability.substvars.new
        mv debian/dump1090-mutability.substvars.new debian/dump1090-mutability.substvars
        echo "# Automatically added by dh_pysupport">> debian/dump1090-mutability.postinst.debhelper
        sed "s,#ARGS#, dump1090-mutability.private," /usr/share/debhelper/autoscripts/postinst-python-support >> debian/dump1090-mutability.postinst.debhelper
        echo '# End automatically added section' >> debian/dump1090-mutability.postinst.debhelper
        echo "# Automatically added by dh_pysupport">> debian/dump1090-mutability.prerm.debhelper
        sed "s,#ARGS#, dump1090-mutability.private," /usr/share/debhelper/autoscripts/prerm-python-support >> debian/dump1090-mutability.prerm.debhelper
        echo '# End automatically added section' >> debian/dump1090-mutability.prerm.debhelper
   dh_installinit
        install -d debian/dump1090-mutability/etc/init.d
        install -p -m755 debian/dump1090-mutability.init debian/dump1090-mutability/etc/init.d/dump1090-mutability
        echo "# Automatically added by dh_installinit">> debian/dump1090-mutability.postinst.debhelper
        sed "s/#SCRIPT#/dump1090-mutability/;s/#INITPARMS#/defaults/;s/#ERROR_HANDLER#/exit \$?/" /usr/share/debhelper/autoscripts/postinst-init >> debian/dump1090-mutability.postinst.debhelper
        echo '# End automatically added section' >> debian/dump1090-mutability.postinst.debhelper
        echo "# Automatically added by dh_installinit"> debian/dump1090-mutability.prerm.debhelper.new
        sed "s/#SCRIPT#/dump1090-mutability/;s/#INITPARMS#/defaults/;s/#ERROR_HANDLER#/exit \$?/" /usr/share/debhelper/autoscripts/prerm-init >> debian/dump1090-mutability.prerm.debhelper.new
        echo '# End automatically added section' >> debian/dump1090-mutability.prerm.debhelper.new
        cat debian/dump1090-mutability.prerm.debhelper >> debian/dump1090-mutability.prerm.debhelper.new
        mv debian/dump1090-mutability.prerm.debhelper.new debian/dump1090-mutability.prerm.debhelper
        echo "# Automatically added by dh_installinit"> debian/dump1090-mutability.postrm.debhelper.new
        sed "s/#SCRIPT#/dump1090-mutability/;s/#INITPARMS#/defaults/;s/#ERROR_HANDLER#/exit \$?/" /usr/share/debhelper/autoscripts/postrm-init >> debian/dump1090-mutability.postrm.debhelper.new
        echo '# End automatically added section' >> debian/dump1090-mutability.postrm.debhelper.new
        cat debian/dump1090-mutability.postrm.debhelper >> debian/dump1090-mutability.postrm.debhelper.new
        mv debian/dump1090-mutability.postrm.debhelper.new debian/dump1090-mutability.postrm.debhelper
   dh_installlogrotate
        install -o 0 -g 0 -d debian/dump1090-mutability/etc/logrotate.d
        install -m 644 debian/dump1090-mutability.logrotate debian/dump1090-mutability/etc/logrotate.d/dump1090-mutability
   dh_perl
   dh_link
   dh_compress
        cd debian/dump1090-mutability
        chmod a-x usr/share/doc/dump1090-mutability/changelog
        gzip -9nf usr/share/doc/dump1090-mutability/changelog
        cd '/home/joe/dump1090'
   dh_fixperms
        find debian/dump1090-mutability  -print0 2>/dev/null | xargs -0r chown --no-dereference 0:0
        find debian/dump1090-mutability ! -type l  -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
        find debian/dump1090-mutability/usr/share/doc -type f  ! -regex 'debian/dump1090-mutability/usr/share/doc/[^/]_/examples/._' -print0 2>/dev/null | xargs -0r chmod 644
        find debian/dump1090-mutability/usr/share/doc -type d  -print0 2>/dev/null | xargs -0r chmod 755
        find debian/dump1090-mutability/usr/share/man debian/dump1090-mutability/usr/man/ debian/dump1090-mutability/usr/X11_/man/ -type f  -print0 2>/dev/null | xargs -0r chmod 644
        find debian/dump1090-mutability -perm -5 -type f ( -name '_.so._' -or -name '_.so' -or -name '_.la' -or -name '_.a' )  -print0 2>/dev/null | xargs -0r chmod 644
        find debian/dump1090-mutability/usr/include -type f  -print0 2>/dev/null | xargs -0r chmod 644
        find debian/dump1090-mutability/usr/share/applications -type f  -print0 2>/dev/null | xargs -0r chmod 644
        find debian/dump1090-mutability -perm -5 -type f ( -name '_.cmxs' )  -print0 2>/dev/null | xargs -0r chmod 644
        find debian/dump1090-mutability/usr/lib/x86_64-linux-gnu/perl5/5.20 debian/dump1090-mutability/usr/share/perl5 -type f -perm -5 -name '_.pm'  -print0 2>/dev/null | xargs -0r chmod a-X
        find debian/dump1090-mutability/usr/bin -type f  -print0 2>/dev/null | xargs -0r chmod a+x
        find debian/dump1090-mutability/etc/init.d -type f  -print0 2>/dev/null | xargs -0r chmod a+x
        find debian/dump1090-mutability/usr/lib -type f -name '_.ali'  -print0 2>/dev/null | xargs -0r chmod uga-w
   dh_strip
        strip --remove-section=.comment --remove-section=.note debian/dump1090-mutability/usr/bin/dump1090-mutability
        strip --remove-section=.comment --remove-section=.note debian/dump1090-mutability/usr/bin/view1090-mutability
   dh_makeshlibs
        rm -f debian/dump1090-mutability/DEBIAN/shlibs
   dh_shlibdeps
        dpkg-shlibdeps -Tdebian/dump1090-mutability.substvars debian/dump1090-mutability/usr/bin/dump1090-mutability debian/dump1090-mutability/usr/bin/view1090-mutability
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/dump1090-mutability/usr/bin/dump1090-mutability was not linked against libusb-1.0.so.0 (it uses none of the library's symbols)
   dh_installdeb
        perl -pe 's~#DEBHELPER#~qx{cat debian/dump1090-mutability.postinst.debhelper}~eg' < debian/dump1090-mutability.postinst > debian/dump1090-mutability/DEBIAN/postinst
        chown 0:0 debian/dump1090-mutability/DEBIAN/postinst
        chmod 755 debian/dump1090-mutability/DEBIAN/postinst
        printf '#!/bin/sh
set -e
' > debian/dump1090-mutability/DEBIAN/prerm
        cat debian/dump1090-mutability.prerm.debhelper >> debian/dump1090-mutability/DEBIAN/prerm
        chown 0:0 debian/dump1090-mutability/DEBIAN/prerm
        chmod 755 debian/dump1090-mutability/DEBIAN/prerm
        perl -pe 's~#DEBHELPER#~qx{cat debian/dump1090-mutability.postrm.debhelper}~eg' < debian/dump1090-mutability.postrm > debian/dump1090-mutability/DEBIAN/postrm
        chown 0:0 debian/dump1090-mutability/DEBIAN/postrm
        chmod 755 debian/dump1090-mutability/DEBIAN/postrm
        install -o 0 -g 0 -m 644 -p debian/dump1090-mutability.conffiles debian/dump1090-mutability/DEBIAN/conffiles
        find debian/dump1090-mutability/etc -type f -printf '/etc/%P
' | LC_ALL=C sort >> debian/dump1090-mutability/DEBIAN/conffiles
        chmod 644 debian/dump1090-mutability/DEBIAN/conffiles
   dh_gencontrol
        dpkg-gencontrol -pdump1090-mutability -ldebian/changelog -Tdebian/dump1090-mutability.substvars -Pdebian/dump1090-mutability
dpkg-gencontrol: warning: package dump1090-mutability: unused substitution variable ${python:Depends}
        chmod 644 debian/dump1090-mutability/DEBIAN/control
        chown 0:0 debian/dump1090-mutability/DEBIAN/control
   dh_md5sums
        (cd debian/dump1090-mutability >/dev/null ; find . -type f ! -path "./usr/share/dump1090-mutability/html/config.js" ! -path "./usr/share/dump1090-mutability/html/gmap.html" ! -path "./usr/share/dump1090-mutability/html/script.js" ! -path "./usr/share/dump1090-mutability/html/planeObject.js" ! -path "./usr/share/dump1090-mutability/html/style.css" ! -path "./usr/share/dump1090-mutability/html/markers.js" ! -path "./usr/share/dump1090-mutability/html/formatter.js" ! -path "./usr/share/dump1090-mutability/html/dbloader.js" ! -path "./etc/init.d/dump1090-mutability" ! -path "./etc/lighttpd/conf-available/89-dump1090.conf" ! -path "./etc/logrotate.d/dump1090-mutability" ! -path "./etc/nginx/sites-available/dump1090-mutability"  ! -regex './DEBIAN/._' -printf '%P\0' | LC_ALL=C sort -z | xargs -r0 md5sum > DEBIAN/md5sums) >/dev/null
        chmod 644 debian/dump1090-mutability/DEBIAN/md5sums
        chown 0:0 debian/dump1090-mutability/DEBIAN/md5sums
   dh_builddeb
        dpkg-deb --build debian/dump1090-mutability ..
dpkg-deb: building package `dump1090-mutability' in`../dump1090-mutability_1.15~dev_amd64.deb'.
 dpkg-genchanges -b >../dump1090-mutability_1.15~dev_amd64.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source --after-build dump1090
dpkg-buildpackage: binary-only upload (no source included)

When trying to install however I receive the following output:

joe@debian:~$ sudo dpkg -i dump1090-mutability_1.15~dev_amd64.deb
Selecting previously unselected package dump1090-mutability.
(Reading database ... 36734 files and directories currently installed.)
Preparing to unpack dump1090-mutability_1.15~dev_amd64.deb ...
Unpacking dump1090-mutability (1.15~dev) ...
Setting up dump1090-mutability (1.15~dev) ...
dpkg: error processing package dump1090-mutability (--install):
 subprocess installed post-installation script returned error exit status 10
Processing triggers for systemd (215-17+deb8u2) ...
Errors were encountered while processing:
 dump1090-mutability

**Comment by jprochazka** [comment]
Looking into things further it appears the package did install. rerunning the command sudo dpkg -i dump1090-mutability_1.15~dev_amd64.deb results in the package being reinstalled and the configuration screen appearing asking for the user to run dump-1090 then where to place the log files. I specified the user joe which I am curenttly logged in as and /var/log/ and /var/log/dump1090-mutability. Both times resulted in the following output.

joe@debian:~$ sudo dpkg -i dump1090-mutability_1.15~dev_amd64.deb
(Reading database ... 36996 files and directories currently installed.)
Preparing to unpack dump1090-mutability_1.15~dev_amd64.deb ...
Unpacking dump1090-mutability (1.15~dev) over (1.15~dev) ...
Setting up dump1090-mutability (1.15~dev) ...
dpkg: error processing package dump1090-mutability (--install):
 subprocess installed post-installation script returned error exit status 10
Processing triggers for systemd (215-17+deb8u2) ...
Errors were encountered while processing:
 dump1090-mutability

**Comment by mutability** [comment]
If you turn on debconf debugging it'll probably tell you something useful.

**Comment by jprochazka** [comment]
ran sudo dpkg --debug=3773 -i  dump1090-mutability_1.15~dev_amd64.deb.

Everything looks good as far as the installation goes. There is A LOT of output of course so only posting the output pertaining to the error. However if you want the full output I can get that to you.

D000002: fork/exec /var/lib/dpkg/info/dump1090-mutability.postinst ( configure  )
dpkg: error processing package dump1090-mutability (--install):
 subprocess installed post-installation script returned error exit status 10
D000001: ensure_diversions: same, skipping
Processing triggers for systemd (215-17+deb8u2) ...
D000002: fork/exec /var/lib/dpkg/info/systemd.postinst ( triggered /etc/init.d )
D000001: ensure_diversions: same, skipping
Errors were encountered while processing:
 dump1090-mutability

The error occurs directly after the "Package configuration" screen is displayed asking for the user to run dump1090 as and where to place log files both of which are new. Used to only seeing an option asking if dump1090 should start automatically.

**Comment by mutability** [comment]
see here: http://mdcc.cx/debian/debugging_debian_package_installations.html

Basically this will just be that I broke something in the packaging when I blind-modified it without any testing; it'll get fixed up when I have some time to test it, probably tomorrow

**Comment by jprochazka** [comment]
Sounds good need any more info let me know.

**Comment by mutability** [comment]
```
# DEBCONF_DEBUG=developer DEBIAN_FRONTEND=noninteractive sh -x /var/lib/dpkg/info/dump1090-mutability.postinst configure 1.15~dev
[...]
debconf (developer): starting /var/lib/dpkg/info/dump1090-mutability.postinst configure 1.15~dev
[...]
debconf (developer): <-- GET dump1090-mutability/net-fatsv-port
debconf (developer): --> 10 dump1090-mutability/net-fatsv-port doesn't exist
```
