### ISSUE TITLE
Push data

### ISSUE THREAD

**Issue by Chrisoo** [mutability/dump1090#95]
Is it possible to do the function push data directly to an IP address?

**Comment by mutability** [comment]
I don't understand what you are asking for.

**Comment by Chrisoo** [comment]
Now it is so that the server needs to connect (download data) to dump1090, and if you can do so that dump1090 send data to a server, and the server is listening on the specified port.

**Comment by mutability** [comment]
The dump1090 network code is pretty horrible and I would not really want to add outgoing connections (+ retries etc) to it. You are better off using external tools like socat to do this.

**Comment by mgunther68** [comment]
modesmixer is another option for this scenario.
