### ISSUE TITLE
Max range not working

### ISSUE THREAD

**Issue by wesleygoatley** [mutability/dump1090#97]
I can't seem to make the max-range argument respond as it seems it should - running dump1090 --max-range 50 --net --interactive still clearly gives me a lot of contacts 100km+ away.  Is this a known issue, or something to do with it running net/interactive?

**Comment by mutability** [comment]
Looks like there is a bug where synthetic mlat positions are always accepted regardless of range. I can't reproduce this with off-the-air messages though.

**Comment by wesleygoatley** [comment]
Thanks Oliver - just checked with your new commit, and I'm getting the same
issue - screenshot attached (I'm in Leuven, scale marker visible at the
bottom)

[image: Inline image 1]

On Fri, Feb 5, 2016 at 4:43 PM, Oliver Jowett notifications@github.com
wrote:

> Closed #97 https://github.com/mutability/dump1090/issues/97 via e101351
> https://github.com/mutability/dump1090/commit/e101351b6e2258a19cd13dc13f7c6ea21e25c33b
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mutability/dump1090/issues/97#event-540800680.

## 

---

www.wesleygoatley.com

PGP Key: CF779171
https://pgp.mit.edu/pks/lookup?op=get&search=0x2027B333CF779171

**Comment by mutability** [comment]
Can you resend the image directly to me or post a link or attach it via the github web interface, it looks like github's email-to-issue-comment gateway discards attachments
