### ISSUE TITLE
raw input and output ports are swapped

### ISSUE THREAD

**Issue by bjd** [mutability/dump1090#99]
It seems recently with commit 2b466535deea8eb1dda8ae20989070d3577fc86c the ports for raw input and output got switched around (See dump1090.c line 148).

**Comment by mutability** [comment]
I guess you mean the defaults.

**Comment by bjd** [comment]
Yes, correct. My feeder host uses systemd so I am not using the supplied init script, but a custom systemd service file where I did not have the raw ports explicitly set.
Thanks for the quick fix :)
